name = "marduk-ts"
main = "dist/worker.js"
compatibility_date = "2023-12-18"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "MARDUK_KV"
id = "d1fcd8dbbd35aec43e5499200f6baede"

[[kv_namespaces]]
binding = "TASK_METRICS"
id = "your_task_metrics_namespace_id"

[env.development]
name = "marduk-ts-dev"
vars = { ENVIRONMENT = "development" }

[env.staging]
name = "marduk-ts-staging"
vars = { ENVIRONMENT = "staging" }

[build]
command = "npm run build"
