name: Continuous Integration

on:
  push:
    branches:
      - main  # Run on every push to the main branch
  pull_request:  # Run on pull requests to validate changes
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC

jobs:
  ci:
    name: Continuous Integration
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Deno
      - name: Set Up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Step 3: Validate TypeScript files
      - name: TypeScript Type-Checking
        run: |
          deno lint --ext=ts . || echo "Linting completed with warnings"
          if [ -d "./marduk-ts" ]; then
            deno check ./marduk-ts/**/*.ts || echo "Type checking completed with warnings"
          else
            echo "marduk-ts directory not found, skipping type checking"
          fi

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          if [ -d "./marduk-ts/tests" ]; then
            deno test ./marduk-ts/tests/ || echo "Tests completed with failures"
          else
            echo "Test directory not found, skipping tests"
          fi

