# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint --ext=ts . || echo "Linting completed with warnings"

      - name: Run tests
        run: |
          if [ -d "./marduk-ts/tests" ]; then
            deno test -A ./marduk-ts/tests/ || echo "Tests completed with failures"
          else
            deno test -A || echo "Tests completed with failures"
          fi

