name: Marduk Cycle Test

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  marduk-test:
    name: Run Marduk Cycles
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set Up Deno
      - name: Set Up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      # Step 3: Run Marduk Cycles
      - name: Run Marduk Cycle
        run: |
          for i in {1..6}; do
            echo "Starting Marduk Cycle $i..."
            if [ -f "./src/cycle_simulation.ts" ]; then
              deno run --allow-read --allow-write ./src/cycle_simulation.ts || echo "Failed to run cycle $i"
            elif [ -f "./marduk-ts/cycle_simulation.ts" ]; then
              deno run --allow-read --allow-write ./marduk-ts/cycle_simulation.ts || echo "Failed to run cycle $i"
            else
              echo "Cycle simulation file not found, skipping cycle $i"
            fi
            echo "Cycle $i complete."
            sleep 300 # Wait for 5 minutes before the next cycle
          done

      # Step 4: Commit Changes
      - name: Commit Simulation Results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -d "./sim" ]; then
            git add ./sim
            if [ -n "$(git status --porcelain)" ]; then
              git commit -m "Cycle simulation updates at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "Nothing to commit"
              git push || echo "Failed to push changes"
            else
              echo "No changes to commit"
            fi
          else
            echo "Simulation directory ./sim does not exist, skipping commit"
          fi
