name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Comment on issue  
        run: |
          gh issue comment $ISSUE_NUMBER --body "Thank you for creating this issue. It has been received and will be reviewed."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
