name: Undo Deletion Commit

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  restore-files:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is fetched

      # Step 2: Identify the Previous Commit
      - name: Get Commit Before Deletion
        id: previous_commit
        run: |
          PREVIOUS_COMMIT=$(git rev-parse HEAD~1) # Commit before HEAD
          echo "PREVIOUS_COMMIT=$PREVIOUS_COMMIT" >> $GITHUB_ENV

      # Step 3: Restore Files from Previous Commit
      - name: Restore Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{ env.PREVIOUS_COMMIT }} . || echo "Failed to checkout previous commit"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Restore files after accidental deletion" || echo "Nothing to commit"
          else
            echo "No changes to restore"
          fi

      # Step 4: Push Restored State
      - name: Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "No pending changes to push"
          else
            git push origin main || echo "Failed to push changes"
          fi
