name: Undo Deletion Commit

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  restore-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full commit history is fetched

      # Step 2: Identify the Previous Commit
      - name: Get Commit Before Deletion
        id: previous_commit
        run: |
          PREVIOUS_COMMIT=$(git rev-parse HEAD~1) # Commit before HEAD
          echo "PREVIOUS_COMMIT=$PREVIOUS_COMMIT" >> $GITHUB_ENV

      # Step 3: Restore Files from Previous Commit
      - name: Restore Files
        run: |
          git checkout ${{ env.PREVIOUS_COMMIT }} .
          git add .
          git commit -m "Restore files after accidental deletion"

      # Step 4: Push Restored State
      - name: Push Changes
        run: |
          git push origin main
